import type {
  EngineConfig,
  LogEntry,
  ScriptInfo,
  StatusResponse,
  StoreScript,
  TaskGroup,
  TaskResult,
} from "./types";

export const mockStatus: StatusResponse = {
  state: "idle",
  task: null,
  progress: null,
  uptime: 1935,
  script_count: 12,
};

export const mockScripts: ScriptInfo[] = [
  {
    name: "auto_domain",
    display_name: "自动秘境",
    version: "1.2.0",
    type: "solo_task",
    author: "Lorenzo",
    description: "自动刷秘境，支持选择关卡、次数、树脂类型",
    enabled: true,
  },
  {
    name: "auto_fight",
    display_name: "自动战斗",
    version: "2.0.1",
    type: "solo_task",
    author: "Lorenzo",
    description: "AI 驱动的自动战斗，支持多种队伍配置",
    enabled: true,
  },
  {
    name: "auto_fishing",
    display_name: "自动钓鱼",
    version: "0.5.0",
    type: "solo_task",
    author: "Community",
    description: "自动钓鱼，支持所有鱼种",
    enabled: false,
  },
  {
    name: "auto_cook",
    display_name: "自动烹饪",
    version: "1.0.0",
    type: "solo_task",
    author: "Lorenzo",
    description: "自动烹饪指定菜品",
    enabled: true,
  },
  {
    name: "auto_pick",
    display_name: "自动拾取",
    version: "1.0.0",
    type: "trigger",
    author: "Community",
    description: "自动拾取附近的物品",
    enabled: true,
  },
  {
    name: "auto_skip",
    display_name: "自动跳过",
    version: "1.1.0",
    type: "trigger",
    author: "Community",
    description: "自动跳过对话和过场动画",
    enabled: true,
  },
  {
    name: "auto_domain_pro",
    display_name: "自动秘境 Pro",
    version: "2.0.0",
    type: "solo_task",
    author: "AI_Bot",
    description: "高级自动秘境，支持智能队伍切换和树脂管理",
    enabled: false,
  },
  {
    name: "daily_routine",
    display_name: "每日一条龙",
    version: "1.5.0",
    type: "solo_task",
    author: "Community",
    description: "自动完成每日委托、消耗树脂、领取奖励",
    enabled: false,
  },
  {
    name: "map_navigator",
    display_name: "地图导航",
    version: "0.8.0",
    type: "solo_task",
    author: "Lorenzo",
    description: "自动导航到指定位置",
    enabled: false,
  },
  {
    name: "quick_teleport",
    display_name: "快速传送",
    version: "1.0.0",
    type: "trigger",
    author: "Community",
    description: "检测传送点并快速传送",
    enabled: false,
  },
  {
    name: "shared_utils",
    display_name: "公共工具库",
    version: "1.0.0",
    type: "library",
    author: "Lorenzo",
    description: "提供通用工具函数",
    enabled: true,
  },
  {
    name: "notification_helper",
    display_name: "通知助手",
    version: "1.0.0",
    type: "library",
    author: "Community",
    description: "简化通知发送的工具库",
    enabled: true,
  },
];

export const mockTaskGroups: TaskGroup[] = [
  {
    uuid: "tg-daily-001",
    name: "每日一条龙",
    mode: "sequential",
    retry_count: 1,
    nodes: [
      { script: "auto_domain", alias: "秘境1-7" },
      { script: "auto_domain", alias: "CE-5" },
      { script: "auto_cook", alias: "烹饪" },
    ],
  },
  {
    uuid: "tg-weekend-002",
    name: "周末特供",
    mode: "sequential",
    retry_count: 2,
    nodes: [
      { script: "auto_domain", alias: "CA-5" },
      { script: "auto_fishing", alias: "钓鱼" },
      { script: "auto_domain", alias: "SK-5" },
    ],
  },
  {
    uuid: "tg-resin-003",
    name: "树脂清空",
    mode: "sequential",
    retry_count: 0,
    nodes: [
      { script: "auto_domain", alias: "刷本" },
    ],
  },
];

export const mockLogs: LogEntry[] = [
  { level: "info", message: "引擎启动完成", timestamp: "14:32:15" },
  { level: "info", message: "已加载 12 个脚本", timestamp: "14:32:16" },
  { level: "info", message: "WGC 截图引擎已初始化", timestamp: "14:32:16" },
  { level: "info", message: "全局热键已注册: F9=启动/停止, F12=紧急停止", timestamp: "14:32:17" },
  { level: "info", message: "开始任务: 自动秘境", timestamp: "14:32:20" },
  { level: "debug", message: "截图完成 1.2ms (WGC)", timestamp: "14:32:21" },
  { level: "debug", message: "模板匹配: enter_btn.png → (960, 540) conf=0.92", timestamp: "14:32:21" },
  { level: "info", message: "点击 (960, 540)", timestamp: "14:32:22" },
  { level: "info", message: "第 1/5 次完成", timestamp: "14:32:24" },
  { level: "warn", message: "模板匹配置信度较低: enter_btn.png conf=0.72", timestamp: "14:32:25" },
  { level: "debug", message: "截图完成 1.1ms (WGC)", timestamp: "14:32:26" },
  { level: "info", message: "检测到战斗结束画面", timestamp: "14:32:28" },
  { level: "info", message: "点击领取奖励 (1050, 600)", timestamp: "14:32:30" },
  { level: "info", message: "第 2/5 次完成", timestamp: "14:32:35" },
  { level: "debug", message: "截图完成 1.3ms (WGC)", timestamp: "14:32:36" },
  { level: "info", message: "正在进入秘境...", timestamp: "14:32:38" },
  { level: "info", message: "第 3/5 次进行中", timestamp: "14:32:40" },
];

export const mockRecentTasks: TaskResult[] = [
  {
    name: "自动秘境",
    success: true,
    duration_ms: 125000,
    started_at: "2026-04-30T14:30:00Z",
    completed_at: "2026-04-30T14:32:05Z",
  },
  {
    name: "自动拾取",
    success: true,
    duration_ms: 0,
    started_at: "2026-04-30T14:28:00Z",
    completed_at: "2026-04-30T14:28:00Z",
  },
  {
    name: "自动战斗",
    success: false,
    duration_ms: 45000,
    error: "截图超时",
    started_at: "2026-04-30T14:20:00Z",
    completed_at: "2026-04-30T14:20:45Z",
  },
  {
    name: "自动秘境",
    success: true,
    duration_ms: 180000,
    started_at: "2026-04-30T14:10:00Z",
    completed_at: "2026-04-30T14:13:00Z",
  },
];

export const mockConfig: EngineConfig = {
  capture: {
    method: "auto",
    method_whitelist: [
      "bitblt",
      "print_window",
      "dwm_shared_surface",
      "windows_graphics_capture",
      "dxgi_desktop_duplication",
    ],
    target_type: "window",
    fps_cap: 60,
    display_index: 0,
    crop_mode: "client_only",
    hdr_policy: "auto",
    minimized_behavior: "keep_trying",
    recover_on_resize: true,
    recover_on_monitor_switch: true,
    crop_shadow: true,
    hdr_to_sdr: true,
  },
  hotkeys: {
    toggle_task: "Ctrl+L",
    emergency_stop: "Ctrl+P",
    toggle_overlay: "Ctrl+O",
    pause_resume: "Ctrl+I",
    debug_screenshot: "Ctrl+U",
  },
  hotkey_triggers: {
    scripts: {},
    task_groups: {},
  },
  key_bindings: {
    bindings: {
      attack: "VK_LBUTTON",
      skill: "VK_E",
      burst: "VK_Q",
      jump: "VK_SPACE",
      sprint: "VK_SHIFT",
      interact: "VK_F",
    },
  },
  overlay: {
    enabled: false,
    mode: "minimal",
    opacity: 0.8,
    font_size: 14,
  },
  scripts: {
    data_root: "data",
    auto_update: true,
    subscriptions: [
      { name: "官方源", directory: "main", enabled: true, auto_update: true },
    ],
  },
  triggers: {},
  task_script_params: {},
  notifications: {
    enabled: false,
    level: "warning",
  },
  api: {
    host: "127.0.0.1",
    port: 23330,
    auth_token: "",
  },
  game: {
    game_name: "异环",
    window_title_keyword: "异环",
    process_name: "HTGame.exe",
    game_language: "zh-cn",
    resolution: "1920x1080",
    scale: 1.0,
    dpi: 96,
  },
  advanced: {
    ocr_engine: "paddle_ocr",
    ocr_model_dir: "assets/models/paddleocr",
    ocr_max_side_len: 960,
    ocr_det_threshold: 0.3,
    ocr_rec_threshold: 0.5,
    ocr_batch_size: 8,
    ocr_unclip_ratio: 2.0,
    ocr_presets: {
      performance: {
        max_side_len: 640,
        det_threshold: 0.25,
        rec_threshold: 0.45,
        batch_size: 16,
        unclip_ratio: 1.6,
      },
      balanced: {
        max_side_len: 960,
        det_threshold: 0.3,
        rec_threshold: 0.5,
        batch_size: 8,
        unclip_ratio: 2.0,
      },
      accuracy: {
        max_side_len: 1280,
        det_threshold: 0.35,
        rec_threshold: 0.55,
        batch_size: 4,
        unclip_ratio: 2.4,
      },
    },
    template_match_threshold: 0.8,
    hardware_acceleration: "auto",
    input_mode: "auto",
    foreground_input_backend: "enigo",
    input_rate_limit: 0,
    log_level: "info",
    log_file: "logs/betternte.log",
    log_max_size: 50,
    log_max_files: 5,
    task_groups_file: "task_groups.json",
    debug_screenshot_dir: "",
    debug_mode: false,
  },
  replay: {
    mode: "normal",
    artifact_root: "",
    session_name: "",
    frame_sample_interval: 0,
  },
  security: {
    mode: "normal",
  },
};

export const mockStoreScripts: StoreScript[] = [
  {
    name: "auto_domain_pro",
    display_name: "自动秘境 Pro",
    version: "2.0.0",
    author: "AI_Bot",
    description: "高级自动秘境，支持智能队伍切换、树脂管理、多关卡连续刷取",
    category: "combat",
    rating: 4.8,
    downloads: 12300,
    installed: true,
    update_available: false,
  },
  {
    name: "daily_routine",
    display_name: "一键日常全家桶",
    version: "1.5.0",
    author: "Community",
    description: "包含每日委托、树脂消耗、奖励领取的一键执行流程",
    category: "daily",
    rating: 4.7,
    downloads: 8200,
    installed: true,
    update_available: true,
  },
  {
    name: "smart_fight_ai",
    display_name: "智能战斗 AI",
    version: "3.0.0",
    author: "AI_Bot",
    description: "AI 驱动的自动战斗，支持角色切换、元素反应、走位闪避",
    category: "combat",
    rating: 4.6,
    downloads: 6100,
    installed: false,
    update_available: false,
  },
  {
    name: "auto_pick_enhanced",
    display_name: "自动拾取增强版",
    version: "1.3.0",
    author: "Community",
    description: "增强版自动拾取，支持自定义拾取范围和优先级过滤",
    category: "trigger",
    rating: 4.5,
    downloads: 3200,
    installed: false,
    update_available: false,
  },
  {
    name: "map_navigator",
    display_name: "地图导航",
    version: "0.8.0",
    author: "Lorenzo",
    description: "自动导航到指定位置，支持自定义路径点和避障",
    category: "explore",
    rating: 4.3,
    downloads: 2100,
    installed: false,
    update_available: false,
  },
  {
    name: "notification_forwarder",
    display_name: "通知转发器",
    version: "1.0.0",
    author: "Community",
    description: "支持 Telegram、Discord、Server酱等多渠道通知转发",
    category: "tool",
    rating: 4.1,
    downloads: 1500,
    installed: false,
    update_available: false,
  },
  {
    name: "auto_fishing_master",
    display_name: "钓鱼大师",
    version: "2.1.0",
    author: "Fisher",
    description: "全自动钓鱼，支持所有鱼种识别和最佳收杆时机",
    category: "daily",
    rating: 4.4,
    downloads: 4500,
    installed: false,
    update_available: false,
  },
  {
    name: "artifact_scanner",
    display_name: "圣遗物扫描",
    version: "1.2.0",
    author: "Optimizer",
    description: "OCR 扫描圣遗物属性，自动评分和推荐",
    category: "tool",
    rating: 4.2,
    downloads: 3800,
    installed: false,
    update_available: false,
  },
];
